import { NextResponse } from "next/server";
import { fal } from "@fal-ai/client";
import { createClient } from "@/lib/supabase/server";

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function POST(req: Request) {
    console.log(">>> GENERATE IMAGE API HIT <<<");

    // 1. Authenticate User
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
        console.error("Unauthorized access attempt to create-image API");
        return NextResponse.json(
            { error: "Unauthorized" },
            { status: 401 }
        );
    }

    try {
        const body = await req.json();
        const { prompt, referenceImage } = body;

        if (!prompt) {
            return NextResponse.json(
                { error: "Prompt is required" },
                { status: 400 }
            );
        }

        // Explicitly ensure the FAL_KEY is available for the client
        const rawFalKey = process.env.FAL_KEY;
        if (!rawFalKey) {
            console.error("FAL_KEY is missing from environment variables");
            throw new Error("FAL_KEY is not configured in environment variables.");
        }

        const cleanFalKey = rawFalKey.trim();

        // Explicitly configure the client with the key
        fal.config({
            credentials: cleanFalKey,
        });

        let result;

        // Determine if we are doing standard txt2img or specialized Product Shot
        if (referenceImage) {
            const isWhiteBackground = prompt.toLowerCase().includes("white background") || prompt.toLowerCase().includes("rgb 255,255,255");

            let backgroundUrl;

            if (isWhiteBackground) {
                console.log("Main Hero detection: Using pure white background plate...");
                // Pure white 1x1 pixel base64 for background
                backgroundUrl = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==";
            } else {
                console.log("Step 1: Generating Cinema-Quality Background with Flux 1.1 Pro...");
                const backgroundPrompt = `${prompt}. Cinematic product photography background, empty scene, premium lighting, 8k resolution, highly detailed, photorealistic, elegant composition. IMPORTANT: No product in the center, leave space for placement. No people, no text.`;

                const bgResult = await fal.subscribe("fal-ai/flux-pro/v1.1", {
                    input: {
                        prompt: backgroundPrompt,
                        aspect_ratio: "16:9"
                    } as any,
                    logs: true,
                });

                if (!bgResult.data || !bgResult.data.images || bgResult.data.images.length === 0) {
                    throw new Error("Failed to generate background plate with Flux.");
                }
                backgroundUrl = bgResult.data.images[0].url;
            }

            console.log("Step 2: Integrating product into the scene with Bria...");

            const imageDataUri = referenceImage.startsWith('data:')
                ? referenceImage
                : `data:image/jpeg;base64,${referenceImage}`;

            result = await fal.subscribe("fal-ai/bria/product-shot", {
                input: {
                    image_url: imageDataUri,
                    background_url: backgroundUrl, // Use the high-end generated background
                    scene_description: prompt, // Keep description for shadow matching
                } as any,
                logs: true,
            });
        } else {
            console.log("Using Flux Pro 1.1 for standard generation...");
            result = await fal.subscribe("fal-ai/flux-pro/v1.1", {
                input: {
                    prompt: prompt,
                    aspect_ratio: "16:9"
                } as any,
                logs: true,
            });
        }

        if (!result.data || !result.data.images || result.data.images.length === 0) {
            throw new Error("No image generated by FAL model.");
        }

        const imageUrl = result.data.images[0].url;

        // Fetch the generated image and convert it back to a base64 data URI
        const imageRes = await fetch(imageUrl);
        if (!imageRes.ok) {
            throw new Error(`Failed to fetch the resulting image from ${imageUrl}`);
        }

        const arrayBuffer = await imageRes.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const base64Str = `data:${imageRes.headers.get('content-type') || 'image/jpeg'};base64,${buffer.toString('base64')}`;

        return NextResponse.json({
            image: base64Str
        });

    } catch (error: any) {
        console.error("------------------------------------------------");
        console.error("Generate Image Error Details:");
        console.error("Type:", typeof error);
        console.error("Message:", error.message);
        console.error("Status Code (if any):", error.status);

        let errorMessage = "Failed to generate image with FAL";

        if (typeof error === 'string') {
            errorMessage = error;
        } else if (error && error.message) {
            errorMessage = error.message;
        }

        console.error("Processed Error Message:", errorMessage);
        console.error("FAL_KEY (first 5):", process.env.FAL_KEY ? process.env.FAL_KEY.trim().substring(0, 5) : "MISSING");

        // Improve error message for the user if it's an auth issue
        if (error.status === 401 || (errorMessage && errorMessage.toLowerCase().includes("unauthorized"))) {
            console.error("Detected FAL Authentication Error. Checking key format...");
            errorMessage = "Error de autenticación con FAL. Por favor verifica que la FAL_KEY sea correcta en el archivo .env.local.";
        }

        console.error("Final Error Response Message:", errorMessage);
        console.error("Full Error JSON:", JSON.stringify(error, Object.getOwnPropertyNames(error), 2));
        console.error("------------------------------------------------");

        return NextResponse.json(
            { error: errorMessage },
            { status: 500 }
        );
    }
}
