import { NextResponse } from "next/server";
import { fal } from "@fal-ai/client";

export async function POST(req: Request) {
    console.log(">>> GENERATE IMAGE API HIT <<<");
    try {
        const body = await req.json();
        const { prompt, referenceImage } = body; // referenceImage is a base64 string or data URI

        if (!prompt) {
            return NextResponse.json(
                { error: "Prompt is required" },
                { status: 400 }
            );
        }

        let result;

        // Determine if we are doing standard txt2img or specialized Product Shot
        if (referenceImage) {
            const imageDataUri = referenceImage.startsWith('data:')
                ? referenceImage
                : `data:image/jpeg;base64,${referenceImage}`;

            // Specialized Product Shot model for 1:1 subject integrity (Product Freeze)
            result = await fal.subscribe("fal-ai/bria/product-shot", {
                input: {
                    image_url: imageDataUri,
                    scene_description: prompt,
                    // Bria Product Shot usually doesn't need image_strength 
                    // because it segments the product and freezes it.
                },
                logs: true,
            });
        } else {
            // Fallback for standard high-quality generation if no reference is provided
            result = await fal.subscribe("fal-ai/flux/dev", {
                input: {
                    prompt: prompt,
                },
                logs: true,
            });
        }

        // The result structure from fal.ai usually contains data.images[0].url
        if (!result.data || !result.data.images || result.data.images.length === 0) {
            throw new Error("No image generated by FAL model.");
        }

        const imageUrl = result.data.images[0].url;

        // Fetch the generated image and convert it back to a base64 data URI
        // to maintain compatibility with how the frontend expects the response.
        const imageRes = await fetch(imageUrl);
        if (!imageRes.ok) {
            throw new Error(`Failed to fetch the resulting image from ${imageUrl}`);
        }

        const arrayBuffer = await imageRes.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const base64Str = `data:${imageRes.headers.get('content-type') || 'image/jpeg'};base64,${buffer.toString('base64')}`;

        return NextResponse.json({
            image: base64Str
        });

    } catch (error: any) {
        console.error("------------------------------------------------");
        console.error("Generate Image Error Details:");
        console.error("Message:", error.message);
        console.error("------------------------------------------------");

        return NextResponse.json(
            { error: error.message || "Failed to generate image with FAL" },
            { status: 500 }
        );
    }
}
